# Copyright © 2015 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: Reload systemd
  become: yes
  command: systemctl daemon-reload
  notify:
    - Stop flannel
    - Remove flannel's local subnet config file
    - Start flannel
    - Restart docker

- name: Stop flannel
  become: yes
  service: name={{flanneld_service}} state=stopped

- name: Remove flannel's local subnet config file
  become: yes
  file: path=/run/flannel/ state=absent
  when: remove_local_subnet_config

- name: Start flannel
  become: yes
  service: name={{flanneld_service}} state=started enabled=yes

- name: Restart docker
  become: yes
  service: name=docker.service state=restarted
